### ISSUE TITLE
Transfer Tab Strange Behavior

### ISSUE THREAD

**Issue by bytemon** [mmozeiko/RcloneBrowser#32] opened 2017-03-04 20:05 UTC
OK, performing an "upload".  in the "Transfer" tab, I enter .5M in "Bandwidth" (that's the only limitation field supplied).  I run my rclone "copy".  When finished and ready to run another "upload", (in the "transfer" tab, the .5M has shifted down to the "minimum size" field, and the "Bandwidth" field now reads: ".1M"

**Comment by mmozeiko** [comment] 2017-03-04 20:32
Hmm, I cannot reproduce this.

Can you check one thing for me please - after first transfer finished, (assuming you are using Windows) open registry at `HKEY_CURRENTUSER\Software\rclone-browser\rclone-browser\Transfer` and check the textBandwidth value? Is it `.5M` or not?

**Comment by bytemon** [comment] 2017-03-04 21:10
Upon further review, it looks like "blanking out" the bandwidth and minimum
size fields or restoring defaults (which are blank) does not work - it does
not blank out the registry values.  Then the next time you start an
"upload", the registry values appear in those "transfer tab" limitation
settings.

**Comment by mmozeiko** [comment] 2017-03-05 05:23
Now i see the problem, thanks! This is now fixed, and will be included in next release.

**Closed** 2017-03-05 05:22 UTC
